"""empty message

Revision ID: 907511c31cb2
Revises: fe3c35dc5c23
Create Date: 2026-03-14 14:07:23.633021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '907511c31cb2'
down_revision = 'fe3c35dc5c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_queries')
    op.drop_table('data_entries')
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_column('chart_title')

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_column('rows_count')
        batch_op.drop_column('columns_count')

    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_numeric', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_date', sa.Boolean(), nullable=True))
        batch_op.alter_column('column_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_column('null_count')
        batch_op.drop_column('column_type')
        batch_op.drop_column('unique_values')

    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insight_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('insight_data', sa.JSON(), nullable=True))
        batch_op.drop_column('recommendation')
        batch_op.drop_column('insight_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insight_text', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('insight_data')
        batch_op.drop_column('insight_type')

    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_values', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('column_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('null_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('column_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_date')
        batch_op.drop_column('is_numeric')
        batch_op.drop_column('data_type')

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('columns_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rows_count', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chart_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.create_table('data_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('data_entries_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('data_entries_pkey'))
    )
    op.create_table('chat_queries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('chat_queries_dataset_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_queries_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_queries_pkey'))
    )
    # ### end Alembic commands ###
