"""empty message

Revision ID: aa429d8101df
Revises: 907511c31cb2
Create Date: 2026-03-14 20:01:15.905786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa429d8101df'
down_revision = '907511c31cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('data_questions')
    # ### end Alembic commands ###
