"""empty message

Revision ID: fe3c35dc5c23
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 14:02:59.229821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe3c35dc5c23'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_rows', sa.Integer(), nullable=True),
    sa.Column('file_columns', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('profitability_score', sa.Float(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('prediction_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_queries')
    op.drop_table('data_entries')
    op.drop_table('datasets')
    op.drop_table('reports')
    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('charts_dataset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('chart_title')

    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_numeric', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_date', sa.Boolean(), nullable=True))
        batch_op.alter_column('column_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('dataset_columns_dataset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('null_count')
        batch_op.drop_column('column_type')
        batch_op.drop_column('unique_values')

    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insight_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('insight_data', sa.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('insights_dataset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('recommendation')
        batch_op.drop_column('insight_text')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insight_text', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('insights_dataset_id_fkey'), 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('insight_data')
        batch_op.drop_column('insight_type')

    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_values', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('column_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('null_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dataset_columns_dataset_id_fkey'), 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('column_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_date')
        batch_op.drop_column('is_numeric')
        batch_op.drop_column('data_type')

    with op.batch_alter_table('charts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chart_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('charts_dataset_id_fkey'), 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')

    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('report_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('reports_dataset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_table('datasets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rows_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('columns_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('datasets_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('datasets_pkey'))
    )
    op.create_table('data_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('data_entries_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('data_entries_pkey'))
    )
    op.create_table('chat_queries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('chat_queries_dataset_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_queries_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_queries_pkey'))
    )
    op.drop_table('predictions')
    op.drop_table('business_scores')
    op.drop_table('dataset')
    # ### end Alembic commands ###
